# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GitHubViever' do
  pod 'AFNetworking', '~> 3.0'

  # Pods for GitHubViever

  target 'GitHubVieverTests' do
    inherit! :search_paths
    pod 'AFNetworking', '~> 3.0'
    # Pods for testing
  end

  target 'GitHubVieverUITests' do
    inherit! :search_paths
    pod 'AFNetworking', '~> 3.0'
    # Pods for testing
  end

end
